### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by Bailey-24** [daerduoCarey/where2act#10]
I would appreciate it if you would tell me  where the `where2act_original_sapien_dataset.zip`. I have to run your code.
Thank you very much!

**Comment by JayKamat99** [comment]
Even I am looking for the same thing. Where shall I download the `where2act_original_sapien_dataset.zip` from?

**Comment by JayKamat99** [comment]
Oh! My bad... I should have read the documentation properly.
You can download the dataset by filling [this form](https://docs.google.com/forms/d/e/1FAIpQLSegEvIM22Ta44MrKM5d-guRE4aDR5K77ZQoInLWEyib-aeCFw/viewform?usp=sf_link)
