### ISSUE TITLE
“gripper_direction_world” and "gripper_forward_direction_world"

### ISSUE THREAD

**Issue by HanHan55** [daerduoCarey/where2act#11]
Hi, Kaichun,

What is the difference between “gripper_direction_world” and "gripper_forward_direction_world"  these two parameters？

Best,
Yuhan

**Comment by daerduoCarey** [comment]
the gripper direction is the gripper pointing direction, while the forward direction is a direction that is orthogonal to the gripper direction, one of the two other directions, which form the gripper coordinate with the gripper direction.
