### ISSUE TITLE
cannot install sapien 0.8. There is no whl package in sapien repo.

### ISSUE THREAD

**Issue by akira-l** [daerduoCarey/where2act#13]
`pip install http://download.cs.stanford.edu/orion/where2act/where2act_sapien_wheels/sapien-0.8.0.dev0-cp36-cp36m-manylinux2014_x86_64.whl` command is not available. 

> ERROR: sapien-0.8.0.dev0-cp36-cp36m-manylinux2014_x86_64.whl is not a supported wheel on this platform.

There is no whl package in sapien repo right now. I install sapien 1.0.0rc0 but meet error: 

> ImportError: cannot import name 'PxrMaterial' from 'sapien.core' (/opt/conda/lib/python3.8/site-packages/sapien/core/__init__.py)

**Comment by weiheng-liu** [comment]
How did you solve this issue？

**Comment by akira-l** [comment]
I might be able to solve this problem by reinstalling Python and the PyTorch package, paying special attention to the Python version that must be compatible with Sapien. BTW, this bug has been around for too long, I can't remember the details, but it can definitely be resolved by installing the appropriate version of the package.

**Comment by weiheng-liu** [comment]
thank you very much!
