### ISSUE TITLE
How to test through the interface

### ISSUE THREAD

**Issue by liangxuejingjing** [daerduoCarey/where2act#2]
I successfully ran the code, but I don’t know how to control it through the interface. Is there documentation for this interface?Any help here is appreciated.
![image](https://user-images.githubusercontent.com/34302426/110102836-37f6ce80-7de0-11eb-9743-52b870878943.png)

**Comment by daerduoCarey** [comment]
Please check the SAPIEN official tutorial/document here: https://sapien.ucsd.edu/docs/index.html
