### ISSUE TITLE
every time got the 'unsuccessful interaction'

### ISSUE THREAD

**Issue by liangxuejingjing** [daerduoCarey/where2act#3]
Hi ~ I am back...
When I run the `python collect_data.py 40147 StorageFurniture 0 pushing` , I got this GUI. 
![image](https://user-images.githubusercontent.com/34302426/110481881-03a64980-8123-11eb-8372-02a21cb7605e.png)

But I still don't know how to control this gripper to push a drawer. just wait for it automatically???  And I don't know how to use the object properties. Every time when I press the 'q', I would get the 'unsuccessful interaction'.
![image](https://user-images.githubusercontent.com/34302426/110482778-f9d11600-8123-11eb-899a-ee67b718fbb0.png)

How can I successfully run your code?

**Comment by daerduoCarey** [comment]
Please read the README. This script is for automatic random data sampling.

**Comment by daerduoCarey** [comment]
just to be clear, for "'unsuccessful interaction" it shows, it actually correctly runs the code. For random data collection, and to train Where2Act, you randomly sample a place to try, sometimes it succeeds (a positive data), while most time it fails (a negative data). We use these positive/negative data samples to train the classification problem in where2act.

**Comment by daerduoCarey** [comment]
download the pre-trained models, and use `bash scripts/run_visu_critic_heatmap.sh 40147` or `bash scripts/run_visu_action_heatmap_proposals.sh 40147` to get our predicted results.
