### ISSUE TITLE
Number of samples for each primitive action

### ISSUE THREAD

**Issue by chaoyivision** [daerduoCarey/where2act#5]
Hi Kaichun,

Thanks for releasing the code for this interesting project. When [generating the offline data](https://github.com/daerduoCarey/where2act/tree/main/code#generate-offline-training-data), I guess you might like to change _os.mkdir(out_dir)_ to _os.makedirs(out_dir)_ [at [here](https://github.com/daerduoCarey/where2act/blob/6141c767bcd729a8404c4d6a4198dab70a0c08ce/code/collect_data.py#L42)] to build the target dirs recursively - otherwise, the generation scripts may be interrupted without showing any error messages. 

I wonder whether you could also share the #samples-status for each primitive action when convenient (i.e., how many #samples or #subfolders would be generated inside each folder, like ./data/gt_data-train_10cats_train_data-pulling) for us to monitor the overall generation progress - if we follow your suggested #epoches? Thanks for your time!

**Comment by daerduoCarey** [comment]
If you open the released training logs, e.g. `final_logs/finalexp-model_all_final-pushing-None-train_all_v1/train_log.txt`, at line 9-12, you can see the finally useful data amount. But there could be many more folders that contain failed interaction that are not used.
