### ISSUE TITLE
How to install sapien 0.8 on MacOS

### ISSUE THREAD

**Issue by yimingli1998** [daerduoCarey/where2act#7]
Hi,
Thank you for your work. I successfully run the code on Ubuntu 16.04. However, I can not install sapien v0.8 on MacOS. 
![image](https://user-images.githubusercontent.com/47964136/122660789-c4be7000-d1b6-11eb-9dfd-0b91c413a29e.png)
Could you have some suggestions?

**Comment by daerduoCarey** [comment]
hi, this is not related to the where2act project. Please ask in https://github.com/haosulab/SAPIEN-Release
