### ISSUE TITLE
glfw error

### ISSUE THREAD

**Issue by JasonQSY** [daerduoCarey/where2act#8]
Hi I'm trying to run the demo

```
python collect_data.py 40147 StorageFurniture 0 pushing --no_gui --out_dir output
```

I do not have a ubuntu machine with gui so I'm trying to install it on the server. I use python 3.6 to replicate exactly the same python environment. However, it seems glfw has some error

```
Using default glsl path /private/home/syqian/.conda/envs/sapien/lib/python3.6/site-packages/sapien/glsl_shader/130
Vulkan enabled
error: Could not initialize GLFW
```

I know this is probably more related to sapien. However, after checking the sapien release, I'm not able to find sapien 0.8. https://pypi.org/project/sapien/0.7.1.dev0/#history They only has 0.7.1 has 1.0.0.

I can run sapien 1.0/1.1 demo successfully. So it seems that my glfw is installed correctly.

I wonder if you have any thoughts? Thank you!

**Comment by daerduoCarey** [comment]
This is because there is no X on the server. Please try append `xvfb-run -a python xxx.py`, or you can change the opengl renderer with the latest sapien vulkun render to remove such requirement.

**Comment by JasonQSY** [comment]
Thank you for your quick response! It works and I saw you have already put it into the readme. I missed that and thought it may related to my glfw environment.

> If you want to run on a headless server, simple put xvfb-run -a before any code command that runs the SAPIEN simulator. Install the xvfb tool on your server if not installed.
